version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - llm-net

  api_gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.api_gateway
    container_name: aiagent-api_gateway
    ports:
      - "${API_GATEWAY_PORT:-4000}:8000"
    depends_on:
      - orchestrator
    env_file:
      - .env
    volumes:
      - ./core:/app/core
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

  orchestrator:
    build:
      context: .
      dockerfile: docker/Dockerfile.orchestrator
    volumes:
      - ./apps/orchestrator:/app/orchestrator
      - ./core:/app/core
    ports:
      - "${ORCHESTRATOR_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

  broker:
    build:
      context: .
      dockerfile: docker/Dockerfile.broker
    volumes:
      - ./apps/broker:/app/broker
      - ./core:/app/core
    ports:
      - "${BROKER_PORT:-8001}:8000"
    depends_on:
      - orchestrator
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

  agent_creator:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent_creator
    volumes:
      - ./apps/agent_creator:/app/agent_creator
      - ./core:/app/core
    ports:
      - "${AGENT_CREATOR_PORT:-8011}:8000"
    depends_on:
      - broker
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

  agent_researcher:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent_researcher
    volumes:
      - ./apps/agent_researcher:/app/agent_researcher
      - ./core:/app/core
    ports:
      - "${AGENT_RESEARCHER_PORT:-8012}:8000"
    depends_on:
      - broker
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

  agent_publisher:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent_publisher
    volumes:
      - ./apps/agent_publisher:/app/agent_publisher
      - ./core:/app/core
    ports:
      - "${AGENT_PUBLISHER_PORT:-8013}:8000"
    depends_on:
      - broker
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    networks:
      - llm-net

networks:
  llm-net:
    driver: bridge
