FROM python:3.11-slim

WORKDIR /app

# 공통 필수 패키지
RUN pip install --no-cache-dir uvicorn httpx fastapi python-dotenv



COPY ../../ ./

ENV PYTHONPATH=/app
CMD ["uvicorn", "apps.orchestrator.main:app", "--host", "0.0.0.0", "--port", "8000"]
