FROM python:3.11-slim

WORKDIR /app
COPY ../../requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../apps/agent_model/ ./agent_model/
CMD ["python", "agent_model/main.py"]
