FROM python:3.11-slim

WORKDIR /app

RUN pip install uvicorn httpx fastapi uv
COPY ../../requirements.txt ./
RUN uv pip install --system -r requirements.txt

COPY ../../ ./

ENV PYTHONPATH=/app
CMD ["uvicorn", "apps.broker.main:app", "--host", "0.0.0.0", "--port", "8000"]
